### ISSUE TITLE
Newly elected leaders do not register themselves in followers node

### ISSUE THREAD

**Issue by JKOK005** [JKOK005/nus-monorepo#21]
Bug in current implementation
- Newly elected leaders register themselves to the node value. 
- They should register themselves as a child ephemeral node to the node in /followers

FingerTable.go line 124 

`	data, _ := json.Marshal(f.MyInfo)
	glog.Info("Register self in followers: ", string(data))
	for baseHashGroup, _ := range f.Successors {
		_ = zkCli.SetNodeValue(zkCli.PrependFollowerPath(fmt.Sprintf("%d",
														baseHashGroup)), data)
	}
`

**Comment by stefelmanns** [comment]
Changed to:	
`data, _ := json.Marshal(f.MyInfo)`
`for baseHashGroup, _ := range f.Successors {`
    `_ = zkCli.RegisterEphemeralNode(zkCli.PrependFollowerPath(fmt.Sprintf("%d/", baseHashGroup)), data)`
`}`
