### ISSUE TITLE
Node registers itself as non-local upon Finger table initialization

### ISSUE THREAD

**Issue by JKOK005** [JKOK005/nus-monorepo#22]
Source: FingerTable.go line 38

`
37 >> glog.Infof("Building finger table %s:%d", myAddr, myPort)

38 >> nodeObj := &util.NodeInfo{Addr: myAddr, Port: myPort}

39 >> data, _ := json.Marshal(nodeObj)`

Since NodeInfo has a new field called `isLocal`, not declaring it on initialisation will cause its field to be set to False as default. 

The `isLocal` field should be set to true since the information pertains to the local node.

**Comment by stefelmanns** [comment]
Changed to:
`glog.Infof("Building finger table %s:%d", myAddr, myPort)`
		`nodeObj := &util.NodeInfo{Addr: myAddr, Port: myPort, IsLocal: true}`
		`data, _ := json.Marshal(nodeObj)`

Also adjusted lines 68-70:
`json.Unmarshal(nodeData, nodeInfo)`
`successors[eInt] = *nodeInfo`
to
`json.Unmarshal(nodeData, nodeInfo)`
`nodeInfo.IsLocal = false`
`successors[eInt] = *nodeInfo`
